name: workflo to run scripts on

on:
  push:
    branches:
      - main

jobs:
  run-srcipts:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorion
        uses: actions/checkout@v4

      - name: Dar Privilegios de ejecucion y Ejecutar script
        run: |
          chmod +x ./scripts/info.sh
          ./scripts/info.sh