name: workflo to run scripts on

on:
  push:
    branches:
      - main

jobs:
  run-srcipts:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorion
        uses: actions/checkout@v4

      - name: dar permisos de ejeciucion ...
        run: |  
          chmod +x ./scripts/info.sh

      - name: Ejecutar script ...
        run: |
          ./scripts/info.sh